import Head from "next/head";
import Image from "next/image";

import Hero from "../components/Hero";
import CharacterCarousel from "../components/CharacterCarousel";

import styles from "../styles/Home.module.css";
import CardSection from "../components/CardSection";
import StoreBar from "../components/StoreBar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Game Ranger App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/img/ae.jpg" />
         */}

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/imgs/favicon.ico"
        />
      </Head>
      <Hero />

      <CardSection />

      <StoreBar />
    </div>
  );
}
